### PR TITLE
runner: add a spec file support

### PR DESCRIPTION
**Pull request by lxbsz**
Just add a spec file support to make it easy to build with rpmbuild
or with SUSE's open build service.

### CODE REVIEW

**Comment by mikechristie** [comment]
Could you incorporate the changes in the suse and fedora specs:

https://build.opensuse.org/package/view_file/openSUSE:Factory/tcmu-runner/tcmu-runner.spec?expand=1

http://pkgs.fedoraproject.org/cgit/rpms/tcmu-runner.git/tree/tcmu-runner.spec

For example

1. Don't hard code the install dirs. Use those rpm macors.
2. Build gluster and ceph since we included their deps in the build requires.

Do not copy the distro libtcmu-devel parts.
1. We want to move away from supporting a stable libtcmu for now, so do not do a -devel package, so it is clear that you cannot build against the lib. Maybe we just want to statically build against libtcmu and not install it at all?

**Comment by lxbsz** [comment]
Yes, will update later.
Thanks,

**Comment by lxbsz** [comment]
@mikechristie 
Has updated, please review.

For now didn't contain the libtcmu and -devel parts, this will be added in the future.

Thanks,

**Comment by mikechristie** [comment]
Thanks.

**Pull request merged**
