### PR TITLE
tcmu: add scsi name designator in vpd83 response

### PR DESCRIPTION
**Pull request by tangwenji**
add scsi name designator in vpd83 response;

Signed-off-by: tangwenji <tang.wenji@zte.com.cn>

### CODE REVIEW

**Comment by lxbsz** [comment]
@tangwenji 
Just one suggestion, you'd better split you patch to 3 small one, which should be much easier to review.

**Comment by tangwenji** [comment]
@lxbsz 
thanks，i modified it

**Comment by tangwenji** [comment]
Already updated！！
thanks

**Comment by mikechristie** [comment]
@tangwenji I only see one patch that adds the scsi name support now. Did you mean to upload a patchset in this PR with multiple patches that support scsi names and the cleanup of how we handle pages like in your original patch, or were you going to submit each patch in different PRs?

**Comment by tangwenji** [comment]
@mikechristie thanks your review。
 yes， I‘m going to submit 3 PRs。
The PR is just add scsi name support，
fix vpd00 buf length is already merged #216
I will submit another PR for tcmu_emulate_evpd_inquiry function reconstruct

**Comment by mikechristie** [comment]
Thanks @tangwenji 

I fixed the conflict and merged by hand here:
https://github.com/open-iscsi/tcmu-runner/commit/1bd2046a728f1a83f072df20697157c94536de19
so I am just closing this PR.

**Pull request closed without merging**
