### PR TITLE
Add logger and system config features support

### PR DESCRIPTION
**Pull request by superlibj**
This patch series add logger and system config support.

The logger feature:
For now the log messages will output to system logger. And the non-block feature will be supported in the later series.

The system config feature:
For now it will support 3 type options: int, string and boolean. If the options has been changed in config file, the tcmu-runner, consumer and tcmu-synthesizer daemons should be restarted.
And the dynamic reloading feature will be added later.

Thanks.
BRs

### CODE REVIEW

**Comment by superlibj** [comment]
@agrover and everyone

please help review, thanks.

**Comment by agrover** [comment]
thoughts @pkalever @mikechristie ?

**Comment by agrover** [comment]
This is valuable but not directly related to tcmu-runner's purpose. I'm wondering if https://github.com/rsyslog/liblogging might be worth looking into. Do we envision needing further logging improvements in the future? If so, maybe we should just rely on a lib from the start.

Also, we have a need for getting performance information out of tcmu-runner -- iops, throughput, latency etc. This is related but not the same as logging. Any ideas on how we could best achieve this, either together or separate from logging?

**Comment by liuy** [comment]
liblogging seems inactive (build fixes recently) and looks complicated. What we need is a ring-buffer (in any situations, like logger process hangs or crashed, do not block tcmu daemon) based prink-like solution(can choose to output to std, syslog, file), which might be severel hundred of lines only. Rely on a library is not so charming if we can implement it by less than 1000 lines. (Most probjects has its own logger, partly because no good log library satisfy all the needs)

Accounting might be different story, because it need modify internal data structures while logger doesn't. So I'd suggest separate accounting implementation from logging.

**Comment by superlibj** [comment]
This is the base for TCMU logging, planing to use the least code to support as many features as possible, such as rsyslog, file and so on. In the near future, the ring-buffer will be added for log-safer. For many other projects, they are all using separate implementions of themselives from lib logging to satisfy what they need. 

When all the features has been implemented, the perfomance information of tcmu-runner will be provided.

**Comment by agrover** [comment]
looks good. Please rename tcmu_config_destory to tcmu_config_destroy and I'll merge it.

Thanks much!!!

**Comment by mikechristie** [comment]
It looks ok to me.

I am not sure about perf counter stuff yet.

For config support, have you guys used libs like libconfig?

**Comment by superlibj** [comment]
@agrover okay。

**Comment by superlibj** [comment]
@mikechristie not yet，the config feature will be enhance later, and if needed and possible i will support that.

**Comment by agrover** [comment]
thanks again!

**Pull request merged**
