### PR TITLE
iovec redefiniton for some kernel versions fixed

### PR DESCRIPTION
**Pull request by denis-koptev**

### CODE REVIEW

**Comment by mikechristie** [comment]
This has the same problem as

https://github.com/open-iscsi/tcmu-runner/pull/322

where for older setups it breaks the compilation.

**Comment by denis-koptev** [comment]
@mikechristie Even if it with #ifdef?

**Comment by mikechristie** [comment]
> @mikechristie Even if it with #ifdef?

You mean how you coded right? Yeah, it fails:

> In file included from /root/targetcli/devel/tcmu-runner/libtcmu.c:36:0:
> /root/targetcli/devel/tcmu-runner/target_core_user_local.h:119:17: error: array type has incomplete element type
>     struct iovec iov[0];
>                  ^
> /root/targetcli/devel/tcmu-runner/libtcmu.c: In function ‘tcmulib_get_next_command’:
> /root/targetcli/devel/tcmu-runner/libtcmu.c:994:39: error: dereferencing pointer to incomplete type
>     cmd = malloc(sizeof(*cmd) + sizeof(*cmd->iovec) * ent->req.iov_cnt + cdb_len);
>                                        ^
> /root/targetcli/devel/tcmu-runner/libtcmu.c:1003:5: error: invalid use of undefined type ‘struct iovec’
>      cmd->iovec[i].iov_base = (void *) mb +
>      ^
> /root/targetcli/devel/tcmu-runner/libtcmu.c:1003:15: error: dereferencing pointer to incomplete type
>      cmd->iovec[i].iov_base = (void *) mb +
>                ^
> /root/targetcli/devel/tcmu-runner/libtcmu.c:1005:5: error: invalid use of undefined type ‘struct iovec’
>      cmd->iovec[i].iov_len = ent->req.iov[i].iov_len;
>      ^
> /root/targetcli/devel/tcmu-runner/libtcmu.c:1005:15: error: dereferencing pointer to incomplete type
>      cmd->iovec[i].iov_len = ent->req.iov[i].iov_len;
>                ^
> /root/targetcli/devel/tcmu-runner/libtcmu.c:1009:4: error: invalid use of undefined type ‘struct iovec’
>     cmd->cdb = (uint8_t *) (cmd->iovec + cmd->iov_cnt);
>     ^
> make[2]: *** [CMakeFiles/tcmu.dir/libtcmu.c.o] Error 1
> make[1]: *** [CMakeFiles/tcmu.dir/all] Error 2

**Comment by mikechristie** [comment]
There is a patch in this comment that works for me:

https://github.com/open-iscsi/tcmu-runner/pull/322#issuecomment-400015049

**Comment by mikechristie** [comment]
I merged the fix-comp2.txt patch in the above comment:

https://github.com/open-iscsi/tcmu-runner/commit/6b9dc381e231c93c61efe736698dab69e37d8adf

Open a new PR if there are issues.

**Pull request closed without merging**
