### PR TITLE
libtcmu: fix cfgstring len

### PR DESCRIPTION
**Pull request by pkalever**
cfgstring will look like,
test@192.168.124.208/block-store/c2d55250-9d9d-4965-bfa1-43ce1b3aa5fc (glfs)

The string can exceed 256 characters.

Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

### CODE REVIEW

**Comment by pkalever** [comment]
Sorry for delaying this patch. Now I have made a helper function as per mikes comments. And made the cfgstring len to be 4k.

**Comment by lxbsz** [comment]
Tested by using rbd handler and looks good to me.

**Comment by pkalever** [comment]
@lxbsz thanks!

**Comment by mikechristie** [comment]
Thanks for the patch pkalever and testing and review lxbsz.

**Pull request merged**
