### PR TITLE
rbd: offload compare-and-write operations to the storage cluster

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by dillaman** [comment]
(still testing this)

**Comment by dillaman** [comment]
Note: depends on this PR: https://github.com/ceph/ceph/pull/18708

**Comment by dillaman** [comment]
```
# dd if=block0 of=/dev/sda count=1 bs=512 oflag=sync,direct
# sg_compare_and_write --in=block0 --inw=block1 --lba=0 /dev/sg0
# sg_compare_and_write --in=block0 --inw=block1 --lba=0 /dev/sg0
COMPARE AND WRITE:  Fixed format, current;  Sense key: Miscompare
 Additional sense: Miscompare during verify operation
  Info fld=0x0 [0]
# sg_compare_and_write --in=block2 --inw=block0 --lba=0 /dev/sg0

Miscompare at byte offset: 0 [0x0]
# sg_compare_and_write --in=block1 --inw=block2 --lba=0 /dev/sg0
# sg_compare_and_write --in=block0 --inw=block1 --lba=0 /dev/sg0
COMPARE AND WRITE:  Fixed format, current;  Sense key: Miscompare
 Additional sense: Miscompare during verify operation
  Info fld=0x0 [0] 
Miscompare at byte offset: 0 [0x0]
# sg_compare_and_write --in=block1 --inw=block2 --lba=0 /dev/sg0
COMPARE AND WRITE:  Fixed format, current;  Sense key: Miscompare
 Additional sense: Miscompare during verify operation
  Info fld=0x0 [0] 
Miscompare at byte offset: 0 [0x0]
# cp block2 block2.bad
# truncate -s 256 block2.bad 
# truncate -s 512 block2.bad 
# sg_compare_and_write --in=block2.bad --inw=block2 --lba=0 /dev/sg0
COMPARE AND WRITE:  Fixed format, current;  Sense key: Miscompare
 Additional sense: Miscompare during verify operation
  Info fld=0x100 [256] 
Miscompare at byte offset: 256 [0x100]
```

**Comment by dillaman** [comment]
librbd PR has merged

**Comment by dillaman** [comment]
rebased to handle conflict in ```rbd.c```

**Comment by mikechristie** [comment]
Very nice. Sorry for the delay and breaking the patches so you had to rebase. Thanks!

**Pull request merged**
