### PR TITLE
runner: use ppoll instead of poll

### PR DESCRIPTION
**Pull request by pkalever**
Since we do not want to restart poll from kernel

Suggested-by: Mike Christie <mchristi@redhat.com>
Signed-off-by: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>

### CODE REVIEW

**Comment by mikechristie** [comment]
Hey just debating this with myself.

I know using ppoll was my idea, but I am still not sure if it is uio bug we are hacking around or if we are supposed to be using ppoll for our use. The kernel engineer in me wants to fix the uio/poll code. The lazy userspace engineer in me wants to say merge the patch :)

I think we should at least add a comment in the code and/or better patch description. Maybe:

Use ppoll instead poll to avoid poll call reschedules during signal handling. If we were removing a device, then the uio device's memory could be freed, but the poll would be rescheduled and end up accessing the released device.

**Comment by pkalever** [comment]
> Hey just debating this with myself.
> 
> I know using ppoll was my idea, but I am still not sure if it is uio bug we are hacking around or if we are supposed to be using ppoll for our use. The kernel engineer in me wants to fix the uio/poll code. The lazy userspace engineer in me wants to say merge the patch :)

IMHO, we should let this go as it is a easy/quick fix, and in any point using ppoll is not a bad idea at all. And once you get sometime, may be you can fix it in kernel side ? 

> 
> I think we should at least add a comment in the code and/or better patch description. Maybe:
> 
> Use ppoll instead poll to avoid poll call reschedules during signal handling. If we were removing a device, then the uio device's memory could be freed, but the poll would be rescheduled and end up accessing the released device.

Sure. I can do that.

Thanks :-)

**Comment by mikechristie** [comment]
Ok. Add the requested comment to the code and git commit message, so we can one day figure out why we used ppol. I will merge it for now.

**Comment by pkalever** [comment]
I have refreshed the patch, by adding the comment to git commit. May be you also wanted comment in the code ? Let me do that as well then.

**Comment by pkalever** [comment]
Here is the refreshed version of patch.

**Comment by mikechristie** [comment]
Ok. Thanks.

**Pull request merged**
