### PR TITLE
api: mode sense add rwrecovery page support

### PR DESCRIPTION
**Pull request by lxbsz**
Signed-off-by: Xiubo Li <lixiubo@cmss.chinamobile.com>

### CODE REVIEW

**Comment by mikechristie** [comment]
Where did the retry count values come from?

And what initiator/OS uses this?

**Comment by lxbsz** [comment]
This will be used by some sg3_utils commands ,such as sg_format.

The retry count I just copied from the file_optical.

**Comment by mikechristie** [comment]
I am not sure if that is correct, but I am not sure what the correct value is because it looks like it would depend on the backend devices.

Runner itself does not do any retries, but for example if a Ceph OSD does a read/write() to a SCSI disk, then you would get 5 retries for medium type errors by the SCSI mid layer. If the OSD were using nvme or some other block device then the retry count would be different. Same for file_example and other handlers that end up using local linux disks or remote machines running linux.

Maybe 0 would be safer so the initiator side is not relying on the target to do N retries and will retry itself in some cases. On the other hand, for say a linux SCSI disk use case the SCSI mid layer will retry 5 times and most likely the physical disk will have already retried M times, so we could end up with too many retries.

What do you think?

**Comment by lxbsz** [comment]
I was not very sure too, so just added the counters in the second version.

I do agree that it depends on the specfied backstores, and the runner itself will without any retries.

**Comment by lxbsz** [comment]
Updated.

**Comment by mikechristie** [comment]
Ok. Looks like we at least have similar behavior to the kernel lio code. It looks like scst sets the retry values to 1, so not too different.

Thanks.

**Pull request merged**
