### PR TITLE
glfs: fix build error for GFAPI version check

### PR DESCRIPTION
**Pull request by lxbsz**
If the GFAPI version < 7.6, we will hit:

glfs.c:570:19: error: operator '<' has no left operand
^

Signed-off-by: Xiubo Li <xiubli@redhat.com>

### CODE REVIEW

**Comment by lxbsz** [comment]
It will be the same with https://github.com/gluster/gluster-block/pull/178.

**Comment by pkalever** [comment]
@lxbsz my build failes like:
```
[ 53%] Building C object CMakeFiles/handler_glfs.dir/glfs.c.o
/root/tcmu-runner/glfs.c:570:21: error: #if with no expression
 #if GFAPI_VERSION760
                     ^
make[2]: *** [CMakeFiles/handler_glfs.dir/build.make:63: CMakeFiles/handler_glfs.dir/glfs.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:216: CMakeFiles/handler_glfs.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by lxbsz** [comment]
@pkalever 
Updated done, could you have a try again ?
Thanks

**Comment by pkalever** [comment]
> @pkalever
> Updated done, could you have a try again ?

Thanks @lxbsz.
Works for me now.

But do we need to output:
```
[root@localhost tcmu-runner]# cmake . 
-- checking for module 'glusterfs-api>=7.6'
--   package 'glusterfs-api>=7.6' not found

```

IMO, cmake should be silent here, as long as supported glusterfs-api version is found.

**Comment by lxbsz** [comment]
> > @pkalever
> > Updated done, could you have a try again ?
> 
> Thanks @lxbsz.
> Works for me now.
> 
> But do we need to output:
> 
> ```
> [root@localhost tcmu-runner]# cmake . 
> -- checking for module 'glusterfs-api>=7.6'
> --   package 'glusterfs-api>=7.6' not found
> ```
> IMO, cmake should be silent here, as long as supported glusterfs-api version is found.

Yeah, agree, since this >= 7.6 version is optional here, will silent it.

Thanks.

**Comment by lxbsz** [comment]
@pkalever 
Updated it, please review.
Thanks.

**Comment by pkalever** [comment]
> @pkalever
> Updated it, please review.

Now its silent:

```
[root@localhost tcmu-runner]# cmake .               
-- Configuring done                                 
-- Generating done                                               
-- Build files have been written to: /root/tcmu-runner                                                   
```

Reviewed-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>

**Pull request merged**
