### PR TITLE
rbd: detect pools associated to SSD device class

### PR DESCRIPTION
**Pull request by dillaman**
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

### CODE REVIEW

**Comment by dillaman** [comment]
@mikechristie This PR extracts whether or not a pull is associated to the SSD device class so that you can advertise that back to VMware.

**Comment by dillaman** [comment]
> $ sg_inq --page 0xb1 /dev/sg0 
> VPD INQUIRY: Block device characteristcis page (SBC)
>   **Non-rotating medium (e.g. solid state)**
>   Product type=0
>   WABEREQ=0
>   WACEREQ=0
>   Nominal form factor is not reported
>   VBULS=0

**Comment by dillaman** [comment]
... also verified in ESXi 6.5:

screenshot from 2017-11-02 21-34-36

**Comment by mikechristie** [comment]
Thanks.

**Pull request merged**
