### PR TITLE
tcmu-runner: add possible 12 and 16 bytes CDB debuginfo support.

### PR DESCRIPTION
**Pull request by superlibj**
Signed-off-by: Xiubo Li <lixiubo@cmss.chinamobile.com>

### CODE REVIEW

**Comment by superlibj** [comment]
@agrover Are 12 and 16 bytes CDB possible here ?

**Comment by agrover** [comment]
The initiator might send, yes. 

Btw in default case I think we should set to 6. Otherwise bytes is uninitialized.

**Comment by superlibj** [comment]
Do you mean only default case or together with 3,6,,7 case ?

**Comment by agrover** [comment]
I think it's best to still print something here for all possible CDBs, so we can accurately reflect all cmds we are getting. I don't think we can assume much about vendor-specific CDBs, but surely they're at least 6 bytes, so how about we just use bytes=6 for those cases too? @mikechristie ?

**Comment by mikechristie** [comment]
I think the min is 6 for fixed length.

I think we can ignore variable and extended length CDBs until someone adds support for them.

**Comment by superlibj** [comment]
From the "SCSI Commands Reference Manual.pdf"， the fixed CDB has at least 6 bytes, and the variable CDB has 7 bytes + ADDITIONAL CDB LENGTH (n–7).

The vendor-specific CDBs we just print the first 6 bytes for now. And the varible CDBs will print all of them.
Is that Okay ?

**Comment by mikechristie** [comment]
I think this is a ok.

For future references, you can find more SCSI spec on t10.org. If your company is not a member you can still read the drafts which are helpful. They will have a lot of info that the "SCSI command Reference Manual" is missing.

**Comment by agrover** [comment]
Much thanks!

**Comment by superlibj** [comment]
@mikechristie @agrover Yes and thanks verrry much for you info about the SCSI.

**Comment by liuy** [comment]
@agrover Unfortunately, my company is not a member of t10.org.  Any pointers that we could read those references? Drafts indeed are dry and lack of useful information. Most of the time, lines of codes are much easier to understand for us what an opcode is on earth :(

**Comment by mikechristie** [comment]
Go to http://t10.org/scsi-3.htm. Scroll to the  bottom of the page to "DOCUMENT LINKS".  Click the "here" link. You can only read the drafts for the newest version.

For example for this problem you could open SPC http://www.t10.org/cgi-bin/ac.pl?t=f&f=spc5r13.pdf and in section 4 is where CDBs are described. It is basically what you see in the Seagate manual you referenced but it has more info due to being newer. For example, the Seagate manual I think is missing ALUA commands.

**Pull request merged**
