### PR TITLE
glfs: fix crash for the error path

### PR DESCRIPTION
**Pull request by lxbsz**
From the glfs.h we can know that:

"glfs_fini() must be called after all operations on glfs_t is
finished."

Or it will crash, like here.

Fix issue #361.

Signed-off-by: Xiubo Li <xiubli@redhat.com>

### CODE REVIEW

**Comment by lxbsz** [comment]
https://github.com/open-iscsi/tcmu-runner/issues/361

**Comment by mikechristie** [comment]
Looks ok to me.

@pkalever, @pranithk  and @lxbsz how do you guys want to handle maintainership type of duties for glfs going forward? In the past, I wanted pkalever or pranithk's review before merging glfs changes. Should I assume that if lxbsz is posting a patch it is already internally reviewed and ackd or that lxbsz is maintainer and ok to merge?

**Comment by pranithk** [comment]
@mikechristie We are doing the review on github, so if one of us posts the patch, you can probably hear from one more person before merging it.

**Comment by lxbsz** [comment]
@pkalever 

Yes you are quit right.

@mikechristie 
Since @pkalever's https://github.com/open-iscsi/tcmu-runner/pull/372 has already fix this at the same time, then this patch will be no needed.

**Pull request closed without merging**
