### PR TITLE
tcmu: Fix CMake to install file_optical

### PR DESCRIPTION
**Pull request by bgly**
Signed-off-by: Bryant G. Ly <bly@catalogicsoftware.com>

### CODE REVIEW

**Comment by bgly** [comment]
@mikechristie

**Comment by mikechristie** [comment]
Can you make the building also installation of file_optical optional like the non example handlers? Do a with-file-optical option like glfs/rbd/qcow/zbc.

**Comment by bgly** [comment]
On vacation, but I’ll do try to do it on the phone. I’ll also make the change for file_example.

**Comment by bgly** [comment]
@mikechristie Changes are made

**Pull request merged**
