### PR TITLE
Add support for Debian

### PR DESCRIPTION
**Pull request by JKJameson**

### CODE REVIEW

**Comment by JKJameson** [comment]
ACK

**Comment by mikechristie** [comment]
Thanks. Could could you just roll up all the patches into one patch? We don't want to see the intermediate steps you took to fix up your patches in the main git tree.

**Comment by JKJameson** [comment]
Patch has been rolled up. If you choose #590 over this push, please update the shell in extra/install_dep.sh from sh to bash. The script uses stuff that is only in BASH.

**Comment by mikechristie** [comment]
You responded first so I will merge what you have :) Thanks!

@DifanZhang rebase and update your patches to take into account this PR.

**Pull request merged**
